In [15]:
import os
import pandas as pd
import numpy as np
from statsmodels.stats.proportion import proportions_ztest
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import sklearn.datasets as datasets
from sklearn.tree import DecisionTreeClassifier

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

import sklearn
from sklearn.metrics import confusion_matrix
from xgboost import XGBClassifier
from sklearn.model_selection import KFold, train_test_split, GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_score, recall_score


In [2]:
df_ready=pd.read_csv('df_p.csv')

C:\Users\enabi\anaconda3\envs\untitled\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (361) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
df_ready.shape

(7508, 852)

In [4]:
del df_ready['Unnamed: 0'] 

In [5]:
del df_ready['Date']

In [6]:
del df_ready['Time']

In [8]:
#RF Classifier

X= df_ready.drop(['Final_result'], axis=1)  # Features
y= df_ready['Final_result']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) # 75% training and 25% test

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)


y_pred=clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred) )


Accuracy: 0.5206391478029294


In [9]:
# training_acuuracy

y_pred_train=clf.predict(X_train)

# Model Accuracy, how often is the classifier correct?
print("Accuracy_train:",metrics.accuracy_score(y_train, y_pred_train) )


Accuracy_train: 1.0


In [12]:
clf_cv=RandomForestClassifier(n_estimators=100)
scores = cross_val_score(clf_cv, X_train, y_train, 
scoring='accuracy', cv=10)

In [13]:
scores

array([0.54076539, 0.51913478, 0.51081531, 0.51913478, 0.53078203,
       0.5374376 , 0.50666667, 0.55166667, 0.53666667, 0.53833333])

In [18]:
print(metrics.classification_report(y_test, y_pred, digits=3))

              precision    recall  f1-score   support

         1.0      0.541     0.832     0.655       678
         2.0      0.313     0.081     0.129       381
         3.0      0.519     0.422     0.466       443

    accuracy                          0.521      1502
   macro avg      0.458     0.445     0.417      1502
weighted avg      0.477     0.521     0.466      1502



In [7]:
clf.feature_importances_

array([1.89986073e-03, 7.98275826e-03, 1.07381547e-03, 8.92851968e-04,
       2.82948584e-04, 1.28243829e-03, 2.58647021e-03, 2.59893115e-03,
       2.36462411e-03, 1.79197036e-03, 2.42128970e-03, 1.79386471e-03,
       1.75678782e-03, 2.05292545e-03, 1.65189982e-03, 1.74638104e-03,
       9.64481217e-04, 1.28306140e-03, 3.10897356e-03, 8.49501615e-05,
       1.72202199e-03, 2.22045475e-03, 1.29694055e-03, 1.51409060e-03,
       1.09406621e-03, 1.60131614e-03, 1.08206349e-04, 7.78051935e-03,
       5.08003595e-04, 7.58833077e-05, 2.61145855e-03, 1.20993315e-03,
       4.81366390e-05, 6.83100563e-04, 4.85148721e-03, 2.81880288e-03,
       3.02412444e-03, 7.67656798e-05, 2.54610653e-03, 2.00830838e-03,
       2.74103871e-03, 6.26720931e-05, 1.82455972e-03, 4.68193984e-05,
       3.30597545e-03, 2.34203218e-03, 1.36392787e-04, 1.13040256e-04,
       7.50056748e-04, 2.08511214e-03, 1.28466503e-03, 1.63949557e-03,
       1.74452761e-03, 2.20936296e-03, 1.79317307e-04, 1.03167793e-03,
      

In [8]:
headers = ["name", "score"]
values = sorted(zip(X_train.columns, clf.feature_importances_), key=lambda x: x[1] * -1)
values

[('IWA', 0.009949185803715264),
 ('IWH', 0.008210878252351492),
 ('B365H', 0.007982758260167337),
 ('B365A', 0.0077805193530934205),
 ('WHA', 0.006320691905505865),
 ('LBH', 0.006315716663997426),
 ('WHH', 0.005958012482521619),
 ('LBA', 0.005349910706988014),
 ('BbAvH', 0.005130952042537691),
 ('BbMxA', 0.004851487214978738),
 ('VCH', 0.004259564469728425),
 ('BWA', 0.0040715497232234246),
 ('BWH', 0.003722559493883226),
 ('GBA', 0.003713134474955853),
 ('VCA', 0.003632687319805015),
 ('Away_Fouls_6Away_of_home_mean', 0.0035552091891885755),
 ('Home_Corners_6Home_of_away_sum', 0.003533796424485825),
 ('Home_Shots_6Home_of_away_mean', 0.0034444485230450007),
 ('Home_Corners_6Home_of_away_mean', 0.00338884334232435),
 ('Home_Shots_Home_AllGames_sum_6', 0.00335734137216781),
 ('Home_Shots_HomeTeam_average_6', 0.0033474952171918576),
 ('Home_Shots_HomeTeam_sum_6', 0.0033419645364113014),
 ('Home_Shots_6Home_of_away_sum', 0.0033246310543149243),
 ('BbMxH', 0.003305975447609743),
 ('Home_Sh

In [9]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[593  22  82]
 [284  33  83]
 [203  25 177]]


In [12]:
df_b_m= df_ready.copy()

In [13]:
filt1= df_b_m['Final_result']==2
df_b_m.loc[filt1,'Final_result']=1

In [14]:
filt2= df_b_m['Final_result']==3
df_b_m.loc[filt2,'Final_result']=2

In [15]:
#RF Classifier

X= df_b_m.drop(['Final_result'], axis=1)  # Features
y= df_b_m['Final_result']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1) # 75% training and 25% test

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)


y_pred=clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred) )


Accuracy: 0.7656458055925432


In [16]:
del df_b_m

In [17]:
df_a_m= df_ready.copy()

In [18]:
filt1= df_a_m['Final_result']==3
df_a_m.loc[filt1,'Final_result']=2

In [19]:
#RF Classifier

X= df_a_m.drop(['Final_result'], axis=1)  # Features
y= df_a_m['Final_result']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1) # 75% training and 25% test

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)


y_pred=clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred) )


Accuracy: 0.6338215712383488


In [20]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[210 165]
 [110 266]]


Other rolling_numbers

In [22]:
df_ready3=pd.read_csv('df_p_3.csv')

C:\Users\enabi\anaconda3\envs\untitled\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (36) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [23]:
del df_ready3['Unnamed: 0'] 

In [24]:
del df_ready3['Date']

In [25]:
del df_ready3['Time']

In [26]:
#RF Classifier____3

X= df_ready3.drop(['Final_result'], axis=1)  # Features
y= df_ready3['Final_result']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) # 75% training and 25% test

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)


y_pred=clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred) )


Accuracy: 0.5339547270306259


In [28]:
df_ready8=pd.read_csv('df_p_8.csv')

C:\Users\enabi\anaconda3\envs\untitled\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (264) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [29]:
del df_ready8['Unnamed: 0'] 

In [30]:
del df_ready8['Date']

In [31]:
del df_ready8['Time']

In [33]:
#RF Classifier____8

X= df_ready8.drop(['Final_result'], axis=1)  # Features
y= df_ready8['Final_result']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) # 75% training and 25% test

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)


y_pred=clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred) )


Accuracy: 0.5206391478029294


In [36]:
df_ready10=pd.read_csv('df_p_10.csv')

In [37]:
del df_ready10['Unnamed: 0'] 

In [38]:
del df_ready10['Date']

In [39]:
del df_ready10['Time']

In [41]:
#RF Classifier____10

X= df_ready10.drop(['Final_result'], axis=1)  # Features
y= df_ready10['Final_result']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) # 75% training and 25% test

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)


y_pred=clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred) )


Accuracy: 0.5226364846870839


In [42]:
clf

RandomForestClassifier()

In [43]:
max_depth = list()
for tree in clf.estimators_:
    max_depth.append(tree.tree_.max_depth)

print("avg max depth %0.1f" % (sum(max_depth) / len(max_depth)))

avg max depth 29.9


hazf_features

In [44]:
df_hazf= df_ready.drop(['IWA', 'IWH', 'B365H', 'B365A', 'WHA', 'LBH', 'WHH', 'LBA', 'BbAvH', 'BbMxA', 'VCH', 'BWA', 'BWH', 'GBA', 'VCA'], axis=1)

In [45]:
#RF Classifier

X= df_hazf.drop(['Final_result'], axis=1)  # Features
y= df_hazf['Final_result']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) # 75% training and 25% test

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)


y_pred=clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred) )


Accuracy: 0.5299600532623169


In [50]:
df_ready.columns = df_ready.columns.str.replace("<", "_less_than_")
df_ready.columns = df_ready.columns.str.replace(">", "_more_than_")
df_ready.columns = df_ready.columns.str.replace(",", ".")
df_ready.columns = df_ready.columns.str.replace("\[", ".")
df_ready.columns = df_ready.columns.str.replace("\]", ".")
df_ready.columns = df_ready.columns.str.replace(" ", "_")

In [51]:
# XGBoost
def set_gridsearch_params():
    params = {
        'n_estimators':[30],
        'max_depth':[9],
        'min_child_weight':[1],
        'gamma':[0.0],
        'subsample':[i/10.0 for i in range(6,10)],
        'colsample_bytree':[i/10.0 for i in range(6,10)]
        # 'subsample':[0.95],
        # 'colsample_bytree':[0.95],
    }
    return params


def gridsearch_run(X_train, y_train):

    # Default classified which will be tuned
    xgb_model = XGBClassifier(
        n_estimators=100,
        max_depth=8,
        min_child_weight=1,
        gamma=0,
        subsample=0.5,
        colsample_bytree=0.5,
        learning_rate=0.1, # ok for Gridsearch
        objective='multi:softprob',
        silent=True,
        nthread=1,
        num_class=3
        )

    # A parameter grid for XGBoost
    params = set_gridsearch_params()

    clf = GridSearchCV(xgb_model,
        params,
        cv=list(KFold(n_splits=5, shuffle=True).split(X_train)), # at least 5 splits
        verbose=2,
        scoring='neg_log_loss',
        n_jobs=-1
        )

    grid_result = clf.fit(X_train, y_train.values.ravel())

    print("\n\nBest score: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
    y_pred=clf.predict(X_test)
    print("Accuracy:",metrics.accuracy_score(y_test, y_pred) )
    means = grid_result.cv_results_['mean_test_score']
    stds = grid_result.cv_results_['std_test_score']
    params = grid_result.cv_results_['params']
    print("\nStats:")
    for mean, stdev, param in zip(means, stds, params):
        print("%f (%f) with: %r" % (mean, stdev, param))


In [52]:
X= df_ready.drop(['Final_result'], axis=1)  # Features
y= df_ready['Final_result']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) 
gridsearch_run(X_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  4.7min
[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed: 12.8min finished




Best score: -0.983261 using {'colsample_bytree': 0.8, 'gamma': 0.0, 'max_depth': 9, 'min_child_weight': 1, 'n_estimators': 30, 'subsample': 0.8}
Accuracy: 0.5106524633821571

Stats:
-0.992115 (0.018766) with: {'colsample_bytree': 0.6, 'gamma': 0.0, 'max_depth': 9, 'min_child_weight': 1, 'n_estimators': 30, 'subsample': 0.6}
-0.987253 (0.018565) with: {'colsample_bytree': 0.6, 'gamma': 0.0, 'max_depth': 9, 'min_child_weight': 1, 'n_estimators': 30, 'subsample': 0.7}
-0.986497 (0.015380) with: {'colsample_bytree': 0.6, 'gamma': 0.0, 'max_depth': 9, 'min_child_weight': 1, 'n_estimators': 30, 'subsample': 0.8}
-0.989656 (0.017769) with: {'colsample_bytree': 0.6, 'gamma': 0.0, 'max_depth': 9, 'min_child_weight': 1, 'n_estimators': 30, 'subsample': 0.9}
-0.988535 (0.017058) with: {'colsample_bytree': 0.7, 'gamma': 0.0, 'max_depth': 9, 'min_child_weight': 1, 'n_estimators': 30, 'subsample': 0.6}
-0.988027 (0.014470) with: {'colsample_bytree': 0.7, 'gamma': 0.0, 'max_depth': 9, 'min_child_we

In [55]:
xgb_model = XGBClassifier(
        n_estimators=300,
        max_depth=9,
        min_child_weight=1,
        gamma=0,
        subsample=0.8,
        colsample_bytree=0.8,
        learning_rate=0.1, # ok for Gridsearch
        objective='multi:softprob',
        silent=True,
        nthread=1,
        num_class=3
        )

In [56]:
xgb_model.fit(X_train,y_train)


y_pred=xgb_model.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred) )

Accuracy: 0.5099866844207723


In [57]:
df_ready.index.names

FrozenList([None])

In [90]:
df_ready.index.names = ['index']

In [116]:
pd.set_option('display.max_columns',900)

In [117]:
pd.set_option('display.max_rows',900)

In [118]:
co==pd.DataFrame(df_ready.corr())